---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      env:
        - name: SEC_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SEC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
