---
apiVersion: v1
kind: Pod
metadata:
  name: w5t3-pod
spec:
  containers:
  - name:
    image: gcr.io/k8s-glc/w5-task2:v2.0.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data
      mountPath: /data
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
  volumes:
  - name: data
    hostPath:
      path: /var/lib/w5t3
