apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - name: app-resource
    image: gcr.io/k8s-glc/w5-task2:v2.0.0
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
