apiVersion: apps/v1
kind: Deployment
metadata:
  name: w5-task2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w5-task2
  template:
    metadata:
      labels:
        app: w5-task2
    spec:
      containers:
      - name: w5-task2
        image: gcr.io/k8s-glc/w5-task2:v2.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: w5-task2
spec:
  selector:
    app: w5-task2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080